# Generated by Django 5.1.2 on 2026-04-30 17:53

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('sessions_total', models.PositiveIntegerField(default=0)),
                ('unique_devices', models.PositiveIntegerField(default=0)),
                ('unique_users', models.PositiveIntegerField(default=0)),
                ('listen_seconds', models.PositiveBigIntegerField(default=0)),
                ('peak_concurrent', models.PositiveIntegerField(default=0)),
                ('avg_session_seconds', models.PositiveIntegerField(default=0)),
                ('computed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Daily stats',
                'verbose_name_plural': 'Daily stats',
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='DriverSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Driver segment',
                'verbose_name_plural': 'Driver segments',
                'ordering': ('sort_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='ListenerEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('start', 'Start'), ('heartbeat', 'Heartbeat'), ('track_play', 'Track play'), ('ad_play', 'Ad play'), ('error', 'Error'), ('end', 'End')], max_length=16)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('payload', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Listener event',
                'verbose_name_plural': 'Listener events',
                'ordering': ('-occurred_at',),
            },
        ),
        migrations.CreateModel(
            name='ListenerSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('device_id', models.CharField(blank=True, db_index=True, max_length=128)),
                ('platform', models.CharField(blank=True, help_text='ios/android/web', max_length=16)),
                ('app_version', models.CharField(blank=True, max_length=32)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('country', models.CharField(blank=True, max_length=2)),
                ('state_code', models.CharField(blank=True, max_length=8)),
                ('started_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('last_heartbeat_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Listener session',
                'verbose_name_plural': 'Listener sessions',
                'ordering': ('-started_at',),
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('code', models.CharField(help_text='Qisqa kod, masalan "US-TX", "MIDWEST".', max_length=16, unique=True)),
                ('country', models.CharField(default='US', max_length=2)),
                ('timezone', models.CharField(blank=True, default='America/Chicago', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Region',
                'verbose_name_plural': 'Regions',
                'ordering': ('sort_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='RegionStateMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_code', models.CharField(help_text='ISO subdivision code (US-TX, US-CA, ...).', max_length=8, unique=True)),
            ],
            options={
                'verbose_name': 'Region ↔ state mapping',
                'verbose_name_plural': 'Region ↔ state mappings',
            },
        ),
        migrations.CreateModel(
            name='TrackPlayStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('plays', models.PositiveIntegerField(default=0)),
                ('listen_seconds', models.PositiveBigIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Track play stats',
                'verbose_name_plural': 'Track play stats',
                'ordering': ('-date', '-plays'),
            },
        ),
    ]
