# Generated by Django 5.1.2 on 2026-04-30 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('radio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dailystats',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_stats', to='radio.radiostation'),
        ),
        migrations.AddField(
            model_name='dailystats',
            name='top_track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='radio.audiotrack'),
        ),
        migrations.AddField(
            model_name='listenerevent',
            name='track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='radio.audiotrack'),
        ),
        migrations.AddField(
            model_name='listenersession',
            name='live_broadcast',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listener_sessions', to='radio.livebroadcast'),
        ),
        migrations.AddField(
            model_name='listenersession',
            name='segment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listener_sessions', to='analytics.driversegment'),
        ),
        migrations.AddField(
            model_name='listenersession',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listener_sessions', to='radio.radiostation'),
        ),
        migrations.AddField(
            model_name='listenersession',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listener_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='listenerevent',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='analytics.listenersession'),
        ),
        migrations.AddField(
            model_name='listenersession',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listener_sessions', to='analytics.region'),
        ),
        migrations.AddField(
            model_name='dailystats',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_stats', to='analytics.region'),
        ),
        migrations.AddField(
            model_name='regionstatemapping',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_mappings', to='analytics.region'),
        ),
        migrations.AddField(
            model_name='trackplaystats',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='play_stats', to='radio.audiotrack'),
        ),
        migrations.AddIndex(
            model_name='listenerevent',
            index=models.Index(fields=['session', '-occurred_at'], name='analytics_l_session_d4caea_idx'),
        ),
        migrations.AddIndex(
            model_name='listenerevent',
            index=models.Index(fields=['event_type', '-occurred_at'], name='analytics_l_event_t_2b7279_idx'),
        ),
        migrations.AddIndex(
            model_name='listenersession',
            index=models.Index(fields=['station', '-started_at'], name='analytics_l_station_9ab1b1_idx'),
        ),
        migrations.AddIndex(
            model_name='listenersession',
            index=models.Index(fields=['ended_at', 'last_heartbeat_at'], name='analytics_l_ended_a_2725ab_idx'),
        ),
        migrations.AddIndex(
            model_name='listenersession',
            index=models.Index(fields=['region', '-started_at'], name='analytics_l_region__bb12e9_idx'),
        ),
        migrations.AddIndex(
            model_name='dailystats',
            index=models.Index(fields=['station', '-date'], name='analytics_d_station_ecc18d_idx'),
        ),
        migrations.AddConstraint(
            model_name='dailystats',
            constraint=models.UniqueConstraint(fields=('station', 'date', 'region'), name='analytics_unique_daily_stats_scope'),
        ),
        migrations.AddConstraint(
            model_name='trackplaystats',
            constraint=models.UniqueConstraint(fields=('track', 'date'), name='analytics_unique_track_day'),
        ),
    ]
