# Generated by Django 5.1.2 on 2026-04-30 17:53

import ads.models.ad
import radio.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdPlacementRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('every_n_tracks', models.PositiveSmallIntegerField(default=4, help_text='Har N-trekdan keyin ad chiqaradi.')),
                ('max_consecutive_ads', models.PositiveSmallIntegerField(default=1)),
                ('quiet_hours_start', models.TimeField(blank=True, help_text='Shu vaqtdan boshlab ad chiqarilmaydi.', null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, help_text='Shu vaqtgacha ad chiqarilmaydi.', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.PositiveSmallIntegerField(default=10, help_text='Bir nechta rule mos kelsa — eng yuqori priority oladi.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ad placement rule',
                'verbose_name_plural': 'Ad placement rules',
                'ordering': ('-priority', 'name'),
            },
        ),
        migrations.CreateModel(
            name='AdPlay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('completed', models.BooleanField(default=False)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Ad play',
                'verbose_name_plural': 'Ad plays',
                'ordering': ('-started_at',),
            },
        ),
        migrations.CreateModel(
            name='SponsoredAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('sponsor', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('audio_file', models.FileField(upload_to=ads.models.ad._ad_upload_to, validators=[radio.validators.validate_audio_file])),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('file_size', models.PositiveBigIntegerField(default=0)),
                ('bitrate', models.PositiveIntegerField(blank=True, null=True)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('max_plays_per_day', models.PositiveIntegerField(default=0, help_text='0 — chegarasiz.')),
                ('max_total_plays', models.PositiveIntegerField(default=0, help_text='0 — chegarasiz.')),
                ('weight', models.PositiveSmallIntegerField(default=10, help_text='Yuqori weight — tez-tez chiqadi (0..100).')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('expired', 'Expired')], default='draft', max_length=16)),
                ('play_count_total', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sponsored ad',
                'verbose_name_plural': 'Sponsored ads',
                'ordering': ('-created_at',),
            },
        ),
    ]
