# Generated by Django 5.1.2 on 2026-04-30 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ads', '0001_initial'),
        ('analytics', '0001_initial'),
        ('radio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='adplacementrule',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_rules', to='radio.radiostation'),
        ),
        migrations.AddField(
            model_name='adplay',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ad_plays', to='analytics.region'),
        ),
        migrations.AddField(
            model_name='adplay',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ad_plays', to='analytics.listenersession'),
        ),
        migrations.AddField(
            model_name='adplay',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_plays', to='radio.radiostation'),
        ),
        migrations.AddField(
            model_name='sponsoredad',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sponsoredad',
            name='target_regions',
            field=models.ManyToManyField(blank=True, help_text="Bo'sh — barcha regionlar.", related_name='ads', to='analytics.region'),
        ),
        migrations.AddField(
            model_name='sponsoredad',
            name='target_segments',
            field=models.ManyToManyField(blank=True, help_text="Bo'sh — barcha driverlar.", related_name='ads', to='analytics.driversegment'),
        ),
        migrations.AddField(
            model_name='adplay',
            name='ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plays', to='ads.sponsoredad'),
        ),
        migrations.AddIndex(
            model_name='sponsoredad',
            index=models.Index(fields=['status', 'start_at', 'end_at'], name='ads_sponsor_status_466f31_idx'),
        ),
        migrations.AddIndex(
            model_name='adplay',
            index=models.Index(fields=['ad', '-started_at'], name='ads_adplay_ad_id_2f4ce7_idx'),
        ),
        migrations.AddIndex(
            model_name='adplay',
            index=models.Index(fields=['station', '-started_at'], name='ads_adplay_station_4aaa38_idx'),
        ),
    ]
