# Generated by Django 5.1.2 on 2026-04-28 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Base',
                'verbose_name_plural': 'Bases',
            },
        ),
        migrations.CreateModel(
            name='HealthCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.CharField(help_text='Tekshirilgan komponent (db, redis, celery, ...)', max_length=64)),
                ('status', models.CharField(choices=[('ok', 'OK'), ('degraded', 'Degraded'), ('down', 'Down')], default='ok', max_length=16)),
                ('message', models.TextField(blank=True, help_text="Qo'shimcha xabar yoki xatolik matni")),
                ('latency_ms', models.PositiveIntegerField(blank=True, help_text='Tekshiruv davomiyligi (ms)', null=True)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Health Check',
                'verbose_name_plural': 'Health Checks',
                'ordering': ('-checked_at',),
                'indexes': [models.Index(fields=['component', '-checked_at'], name='main_health_compone_b69db7_idx')],
            },
        ),
    ]
