# Generated by Django 5.1.2 on 2026-04-30 17:53

import django.db.models.deletion
import radio.models.live
import radio.models.track
import radio.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('artist', models.CharField(blank=True, default='Dispatch Radio', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('audio_file', models.FileField(upload_to=radio.models.track._audio_upload_to, validators=[radio.validators.validate_audio_file])),
                ('duration_seconds', models.PositiveIntegerField(default=0, help_text='Avtomatik aniqlanadi (mutagen orqali).')),
                ('file_size', models.PositiveBigIntegerField(default=0)),
                ('mime_type', models.CharField(blank=True, max_length=64)),
                ('sample_rate', models.PositiveIntegerField(blank=True, null=True)),
                ('bitrate', models.PositiveIntegerField(blank=True, help_text='kbps', null=True)),
                ('category', models.CharField(choices=[('news', 'News'), ('music', 'Music'), ('talk', 'Talk / Show'), ('safety', 'Safety / Tips'), ('weather', 'Weather'), ('promo', 'Station promo'), ('jingle', 'Jingle / Bumper'), ('other', 'Other')], default='music', max_length=16)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready'), ('archived', 'Archived')], default='ready', max_length=16)),
                ('play_count', models.PositiveIntegerField(default=0)),
                ('last_played_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('region', models.ForeignKey(blank=True, help_text="Faqat shu region uchun. Bo'sh bo'lsa — universal.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracks', to='analytics.region')),
                ('segments', models.ManyToManyField(blank=True, help_text="Faqat shu segmentlardagi driverlar uchun. Bo'sh — barchasi.", related_name='tracks', to='analytics.driversegment')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_tracks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audio track',
                'verbose_name_plural': 'Audio tracks',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=16)),
                ('is_fallback', models.BooleanField(default=False, help_text="Asosiy playlist tugaganda yoki bo'lmaganda ishlatiladi.")),
                ('auto_repeat', models.BooleanField(default=True, help_text='Playlist tugagach boshidan loop ketadimi.')),
                ('shuffle', models.BooleanField(default=False)),
                ('total_duration', models.PositiveIntegerField(default=0, help_text='Avtomatik hisoblanadi (sekund).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('region', models.ForeignKey(blank=True, help_text="Bo'sh — barcha regionlar uchun.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='playlists', to='analytics.region')),
                ('segment', models.ForeignKey(blank=True, help_text="Bo'sh — barcha driverlar uchun.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='playlists', to='analytics.driversegment')),
            ],
            options={
                'verbose_name': 'Playlist',
                'verbose_name_plural': 'Playlists',
                'ordering': ('-date', '-is_fallback'),
            },
        ),
        migrations.CreateModel(
            name='PlaylistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('planned_start', models.TimeField(blank=True, null=True)),
                ('planned_end', models.TimeField(blank=True, null=True)),
                ('is_skipped', models.BooleanField(default=False)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='radio.playlist')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='playlist_items', to='radio.audiotrack')),
            ],
            options={
                'verbose_name': 'Playlist item',
                'verbose_name_plural': 'Playlist items',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='RadioStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('description', models.TextField(blank=True)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='radio/stations/')),
                ('stream_url', models.URLField(help_text="Mobile app shu URL'ni ochadi (Icecast mount, masalan https://radio.example.com/stream.mp3).")),
                ('bitrate', models.PositiveSmallIntegerField(default=128, help_text='kbps')),
                ('audio_format', models.CharField(default='mp3', max_length=16)),
                ('is_default', models.BooleanField(default=False, help_text="Mobile app station tanlamagan bo'lsa shu kanal beriladi.")),
                ('is_active', models.BooleanField(default=True)),
                ('is_live', models.BooleanField(default=False, help_text="Hozir jonli efir ketayotganini bildiradi (tizim avtomatik o'rnatadi).")),
                ('icecast_mount', models.CharField(default='/stream', help_text='Icecast mount nomi (admin status query uchun).', max_length=64)),
                ('listeners_cached', models.PositiveIntegerField(default=0)),
                ('last_health_check', models.DateTimeField(blank=True, null=True)),
                ('online', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fallback_track', models.ForeignKey(blank=True, help_text='Playlist tugab qolsa shu trek loop ketadi.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fallback_for_stations', to='radio.audiotrack')),
            ],
            options={
                'verbose_name': 'Radio station',
                'verbose_name_plural': 'Radio stations',
                'ordering': ('-is_default', 'name'),
            },
        ),
        migrations.AddField(
            model_name='playlist',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to='radio.radiostation'),
        ),
        migrations.CreateModel(
            name='LiveBroadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('stream_key', models.CharField(default=radio.models.live._generate_stream_key, help_text="DJ Icecast'ga shu kalit bilan ulanadi (sourcepassword).", max_length=64, unique=True)),
                ('mount_point', models.CharField(default='/live', help_text='Icecast mount nomi (live efir).', max_length=64)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('live', 'Live'), ('ended', 'Ended'), ('cancelled', 'Cancelled')], default='scheduled', max_length=16)),
                ('scheduled_start', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('listener_peak', models.PositiveIntegerField(default=0)),
                ('listener_total', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_broadcasts_started', to=settings.AUTH_USER_MODEL)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_broadcasts', to='radio.radiostation')),
            ],
            options={
                'verbose_name': 'Live broadcast',
                'verbose_name_plural': 'Live broadcasts',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='StationState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_started_at', models.DateTimeField(blank=True, null=True)),
                ('current_ends_at', models.DateTimeField(blank=True, null=True)),
                ('is_live', models.BooleanField(default=False)),
                ('listeners', models.PositiveIntegerField(default=0)),
                ('online', models.BooleanField(default=False)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('current_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='radio.playlistitem')),
                ('current_track', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='radio.audiotrack')),
                ('live_broadcast', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='radio.livebroadcast')),
                ('next_track', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='radio.audiotrack')),
                ('station', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='state', to='radio.radiostation')),
            ],
            options={
                'verbose_name': 'Station state',
                'verbose_name_plural': 'Station states',
            },
        ),
        migrations.AddIndex(
            model_name='audiotrack',
            index=models.Index(fields=['status', 'category'], name='radio_audio_status_a8bde9_idx'),
        ),
        migrations.AddIndex(
            model_name='audiotrack',
            index=models.Index(fields=['region', 'status'], name='radio_audio_region__85048d_idx'),
        ),
        migrations.AddIndex(
            model_name='playlistitem',
            index=models.Index(fields=['playlist', 'order'], name='radio_playl_playlis_c8a838_idx'),
        ),
        migrations.AddConstraint(
            model_name='radiostation',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('is_default',), name='radio_only_one_default_station'),
        ),
        migrations.AddIndex(
            model_name='playlist',
            index=models.Index(fields=['station', 'date', 'status'], name='radio_playl_station_0e38e9_idx'),
        ),
        migrations.AddConstraint(
            model_name='playlist',
            constraint=models.UniqueConstraint(fields=('station', 'date', 'region', 'segment'), name='radio_unique_playlist_per_scope'),
        ),
        migrations.AddIndex(
            model_name='livebroadcast',
            index=models.Index(fields=['station', 'status'], name='radio_liveb_station_efda99_idx'),
        ),
    ]
