# Generated by Django 5.1.2 on 2026-04-30 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlistitem',
            name='last_played_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playlistitem',
            name='play_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
