# Generated by Django 5.1.2 on 2026-04-30 21:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0002_playlistitem_last_played_at_playlistitem_play_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('description', models.TextField(blank=True)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='radio/shows/')),
                ('color', models.CharField(default='#10b981', help_text='Hex color for calendar/UI (e.g. #10b981).', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hosted_shows', to=settings.AUTH_USER_MODEL)),
                ('playlist', models.ForeignKey(blank=True, help_text="Playlist that auto-DJs during the show. If empty, the day's default playlist plays.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shows', to='radio.playlist')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shows', to='radio.radiostation')),
            ],
            options={
                'verbose_name': 'Show',
                'verbose_name_plural': 'Shows',
                'ordering': ('station', 'name'),
            },
        ),
        migrations.CreateModel(
            name='ShowEpisode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(db_index=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('listener_peak', models.PositiveIntegerField(default=0)),
                ('listener_total', models.PositiveIntegerField(default=0)),
                ('recording_path', models.CharField(blank=True, help_text='Reserved for future recording feature.', max_length=255)),
                ('live_broadcast', models.ForeignKey(blank=True, help_text='If a DJ went live during this episode.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='show_episodes', to='radio.livebroadcast')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='radio.show')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='show_episodes', to='radio.radiostation')),
            ],
            options={
                'verbose_name': 'Show episode',
                'verbose_name_plural': 'Show episodes',
                'ordering': ('-started_at',),
            },
        ),
        migrations.AddField(
            model_name='stationstate',
            name='current_show_episode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='radio.showepisode'),
        ),
        migrations.CreateModel(
            name='ShowSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], db_index=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='radio.show')),
            ],
            options={
                'verbose_name': 'Show schedule',
                'verbose_name_plural': 'Show schedules',
                'ordering': ('day_of_week', 'start_time'),
            },
        ),
        migrations.AddField(
            model_name='showepisode',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='episodes', to='radio.showschedule'),
        ),
        migrations.AddIndex(
            model_name='show',
            index=models.Index(fields=['station', 'is_active'], name='radio_show_station_64bbf5_idx'),
        ),
        migrations.AddIndex(
            model_name='showschedule',
            index=models.Index(fields=['day_of_week', 'is_active'], name='radio_shows_day_of__f12e7b_idx'),
        ),
        migrations.AddIndex(
            model_name='showepisode',
            index=models.Index(fields=['station', '-started_at'], name='radio_showe_station_46c9f8_idx'),
        ),
        migrations.AddIndex(
            model_name='showepisode',
            index=models.Index(fields=['ended_at'], name='radio_showe_ended_a_f622d1_idx'),
        ),
    ]
