# Generated by Django 5.1.2 on 2026-04-30 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('push_token', models.CharField(max_length=512, unique=True)),
                ('platform', models.CharField(choices=[('ios', 'iOS'), ('android', 'Android'), ('web', 'Web')], max_length=16)),
                ('device_id', models.CharField(blank=True, db_index=True, max_length=128)),
                ('app_version', models.CharField(blank=True, max_length=32)),
                ('locale', models.CharField(blank=True, max_length=16)),
                ('timezone', models.CharField(blank=True, max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('failure_count', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='analytics.region')),
                ('segment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='analytics.driversegment')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Device',
                'verbose_name_plural': 'Devices',
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='PushCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('body', models.TextField()),
                ('payload', models.JSONField(blank=True, default=dict, help_text='deep_link, image_url va h.k.')),
                ('target_platform', models.CharField(blank=True, choices=[('ios', 'iOS'), ('android', 'Android'), ('web', 'Web')], help_text="Bo'sh — barcha platformalarga.", max_length=16)),
                ('scheduled_for', models.DateTimeField(blank=True, help_text="Bo'sh — saqlangach darhol jo'natiladi.", null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('queued', 'Queued'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed')], default='draft', max_length=16)),
                ('sent_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='push_campaigns', to=settings.AUTH_USER_MODEL)),
                ('target_region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='analytics.region')),
                ('target_segment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='analytics.driversegment')),
            ],
            options={
                'verbose_name': 'Push campaign',
                'verbose_name_plural': 'Push campaigns',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PushDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('error', models.TextField(blank=True)),
                ('provider_message_id', models.CharField(blank=True, max_length=128)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='notifications.pushcampaign')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='notifications.device')),
            ],
            options={
                'verbose_name': 'Push delivery',
                'verbose_name_plural': 'Push deliveries',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['platform', 'is_active'], name='notificatio_platfor_92aabf_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['region', 'segment', 'is_active'], name='notificatio_region__57da84_idx'),
        ),
        migrations.AddIndex(
            model_name='pushdelivery',
            index=models.Index(fields=['campaign', 'status'], name='notificatio_campaig_d32253_idx'),
        ),
        migrations.AddConstraint(
            model_name='pushdelivery',
            constraint=models.UniqueConstraint(fields=('campaign', 'device'), name='notifications_unique_campaign_device'),
        ),
    ]
